spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.98.149.61:3306/fbstore
  application:
    name: fb-store
  profiles:
    active: pro    #指定对应的生产环境配置文件
  devtools:
    restart:
      additional-paths: src/main/java
      exclude: WEB-INF/**
      enabled: true
  freemarker:
    cache: false
# 阿里云Oss对象存储配置
  cloud:
    alicloud:
      secret-key: O8chr38e5IgiwN2Q5YYJZTDO4kKMRp
      access-key: LTAI5tP5fmky5o7CM5HFaeco
      oss:
        bucket: fb-store
        endpoint: oss-cn-hangzhou.aliyuncs.com
#MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1  #逻辑删除
      logic-not-delete-value: 0
#端口号
server:
  port: 10002


